### PR TITLE
Add highlight_path_spline mode

### PR DESCRIPTION
**Pull request by zhewang**
note: hover events are not working

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
This is a good start! We'll have to think about how to integrate splines better with the current drawing code. 

For example, it isn't happening with the current examples, but what if the topology changes while there are paths showing? The splines should update to the new positions. This feature is on the horizon.

In terms of general GitHub protocol, here are a couple of tips:
 * it's usually a good idea to start a branch for contributing a PR. that way you can continue to push to your master branch without updating the PR.
 * different projects work different ways, but it's usually better not to push any artifacts to the PR. this means not checking in `dc.graph.*` - they just add noise to the diffs.

Please continue working on the hover behavior and think about the possibly changing positions. 
We'll do a more thorough review once you have the hover working.

**Comment by gordonwoodhull** [comment]
With the engineering side out of the way, here are some things to consider on the research side.

Our top concern is readability, so is there anything we can do to simplify and clarify the display?

1. As you mentioned, we can figure out how to do edge bundling to remove some of the noise of multiple strands running in parallel between the same nodes. What are the conditions where bundling the edges between two nodes is correct? I think the Blaas & Botha paper talks about this. 
Also, we have three different kinds of paths, so what should we do when part of a bundle is hover-highlighted, or selected? Notice that both the highlighting and hovering sets can include multiple paths, so how do we indicate what portion of the queried paths are included in either of the other sets?
2. Are there any extraneous bends or loops in the splines? Can different spline parameters help here?
3. Is there anything else we can do to reduce visual noise?

**Comment by gordonwoodhull** [comment]
For the sake of discussion, I'm attaching a couple of screenshots.

Paths on the VM layer:

image

One thing that stands out here is that the splines are nowhere near the underlying edges. In general we can't expect them to be too close, but we might consider if there is anything we can do to make the correspondence clearer, either through color or interaction.

Paths on the VFC layer. There are some weird bends here - kind of looks like the splines have too much "velocity" and are having difficulty making the turns in time.

image

(Note that we currently display edges in the layer views with more detail than we need: we're drawing two edges for each connection, where it's really one bidirectional connection. So the "background" can be simpler too.)

**Comment by cscheid** [comment]
I wonder if there's a way to take the splines into account when optimizing the positioning of the vertices.

**Comment by gordonwoodhull** [comment]
Technically I think it would be possible, because CoLa supports general constraints. 

I looked into implementing custom constraints at one point, and it looked fairly sensible. However, I never found the time to follow through on that.

**Comment by gordonwoodhull** [comment]
Replaced by #58

**Pull request closed without merging**
