### PR TITLE
draw dedicated loops separately

### PR DESCRIPTION
**Pull request by zhewang**

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Looks like you initially appended the loops to the same Bezier string, but then you decided they needed to be drawn separately? In a quick test it seemed to work if I let `genPath` append the loops to the path - what problems did you run into?

**Comment by zhewang** [comment]
It's about the data. 
`var edge = _layer.selectAll(".spline-edge").data(paths, function(path) { return path_keys(path).join(','); });
`
This binds the uniq() processed paths to edges. I will not be able to get loops when calling 
 `.attr('d', function(d) { return genPath(d, true, true, false, pathprops.lineTension, _behavior.avoidSharpTurns()); });
`
If I bind the original path data (without call uniq()) to `edge`, it'll crash many things as I mentioned in an earlier email.

**Comment by gordonwoodhull** [comment]
It seems to work for me, wonder what I am missing. The `path_keys` call there is only for the key for the data join - the bound data is unchanged. (And it would work just as well to call `path_keys(path, false)` if there were paths that only differed by self-loops.)

I guess I'll hold off a few days on merging this, as I'd like the highlighting and transitions to work. In my experiment, they seemed to work except that the loops started flat. I'll look at it when I have a bit more time.

I just did 

```diff
@@ -353,7 +353,7 @@ dc_graph.draw_spline_paths = function(pathreader, pathprops, hoverprops, selectp
             .attr('id', function(d, i) { return "spline-path-"+i; })
             .attr('stroke-width', pathprops.edgeStrokeWidth || 1)
             .attr('fill', 'none')
-            .attr('d', function(d) { return genPath(d, true, true, false, pathprops.lineTension, _behavior.avoidSharpTurns()); });
+            .attr('d', function(d) { return genPath(d, true, true, true, pathprops.lineTension, _behavior.avoidSharpTurns()); });
         edge
             .attr('stroke', function(p) {
                 return selected.indexOf(p) !== -1 && selectprops.edgeStroke ||
@@ -376,26 +376,26 @@ dc_graph.draw_spline_paths = function(pathreader, pathprops, hoverprops, selectp
         _layer.selectAll('.spline-edge-hover')
             .each(function() {this.parentNode.appendChild(this);});
         edge.transition().duration(_behavior.parent().transitionDuration())
-            .attr('d', function(d) { return genPath(d, false, true, false, pathprops.lineTension, _behavior.avoidSharpTurns()); });
+            .attr('d', function(d) { return genPath(d, false, true, true, pathprops.lineTension, _behavior.avoidSharpTurns()); });
```

And commented out the self-loop drawing.

**Comment by zhewang** [comment]
What you did was actually what I was trying to do.

Now I tested appending loops to the Bezier string, it works! Maybe it's because I was developing on an older version of `develop` branch.

**Comment by gordonwoodhull** [comment]
Great! Please simplify this (those extra arguments shouldn't be needed now, nor the special drawing code) and I'll merge.

**Comment by gordonwoodhull** [comment]
Thanks @zhewang! Cleaned up a little more (and made self-loops always have width) and merged.

**Pull request closed without merging**
